### ISSUE TITLE
how to get the wi-sun decryption key

### ISSUE THREAD

**Issue by mcuxmx** [PelionIoT/nanostack-border-router#241]
I got the GTK value from KV storage through "pae_nw_info", and input it into wireshark->Preferences->Protocols->IEEE802.15.4->Decryption Keys
But the message received by the sniffer is still encrypted.
How can I get the correct key.

**Comment by mikaleppanen** [comment]
On Wireshark you'll need to set the group AES key (GAK) as decryption key. GTK needs to be hashed with network name to get that (ch. 6.5.4.1.1 on wisun fan specification), On ws_pae_controller.c there are also extra debug traces under the flag EXTRA_DEBUG_INFO that print the GAK.
