### ISSUE TITLE
how to forward multicast from backhaul to mesh

### ISSUE THREAD

**Issue by mcuxmx** [PelionIoT/nanostack-border-router#242]
I use UDPSocket to open backhaul interface and join multicast address on BR side.
And use UDPSocket to open wisun interface and join multicast address on node side.

Only BR can receive data in backhaul network, wisun node cannot receive multicast data.

how to forward multicast from backhaul network to wisun network?

**Comment by mikter** [comment]
Border router will forward Site scope or larger multicast packets to and from Mesh to backbone. This was verified using latest software
